menu:
  Home: /
  Archives: /archives/
  pics: /pics/

# whether to show read more button when showing article in excerpt in main page
read_more_btn: true

footer:
  # Specify the date when the site was setup. If not defined, current year will be used.
  since: 2014
  beian: 湘ICP备2020021380号-1
  
# baidu analytics
baiduTrackId: 83fbb968d837cac86cb15c97ddd8cdd4

readmore:
  # 是否启用
  enable: true
  # 已申请的博客 ID
  blogId: '31136-1676194002310-704'
  # 已申请的微信公众号名称
  name: '浪漫宇宙与人间日常'
  # 已申请的微信公众号回复关键词
  keyword: '人间日常'
  # 已申请的微信公众号二维码图片
  qrcode: '/qrcode.jpg'
  # 自定义的 JS 资源链接，可用于 CDN 加速
  libUrl: '/js/readmore/readmore.js'
  # 自定义的 CSS 资源链接，可用于适配不同风格的博客
  cssUrl: '/js/readmore/readmore.css'

google-adsense:
   # 是否启用
  enable: true
